### ISSUE TITLE
Export-NAVCumulativeUpdateApplicationObjects fails on non-default instance of SQL server

### ISSUE THREAD

**Issue by JuricaB** [waldo1001/Cloud.Ready.Software.PowerShell#12]
Function only works if NAV is installed on single-instanced SQL server. 
Should be checking $ServerInstanceObject.DatabaseInstance and generate full name from $ServerInstanceObject.DatabaseServer and $ServerInstanceObject.DatabaseInstance (e.g. SERVERNAME\INSTANCENAME).

Currently it errors out with SQL permission error in this case.

**Comment by waldo1001** [comment]
Should be solved with:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/commit/b2c840fde161ee641fc9d24cd0668104128f3f4a

basically, I'm using my new functions now to export objects (that solves the issue).  IN the meanwhile, I also moved the logic to a somewhat more generic function name (Export-NAVApplicationObjects_BasedOnObjectfile)

**Comment by waldo1001** [comment]
Oh .. and thanks for mentioning this! :-)
