### ISSUE TITLE
Unlock-NAVApplicationObjects

### ISSUE THREAD

**Issue by PeterBizz** [waldo1001/Cloud.Ready.Software.PowerShell#14]
Seems that this function ( NAV2016) version has reversed the check for the Database Instance: 

version I have reads: 
   if ([string]::IsNullOrEmpty($ServerInstanceObject.DatabaseInstance)){
        $DatabaseServer = $ServerInstanceObject.DatabaseServer + "\" + $ServerInstanceObject.DatabaseInstance    
   } Else {
   $DatabaseServer = $ServerInstanceObject.DatabaseServer
       
   }

I think it should be : 
 if ([string]::IsNullOrEmpty($ServerInstanceObject.DatabaseInstance)){
       $DatabaseServer = $ServerInstanceObject.DatabaseServer
   } Else {
        $DatabaseServer = $ServerInstanceObject.DatabaseServer + "\" + $ServerInstanceObject.DatabaseInstance
        
   }

I am not familiar to git so please explain me if I need to report this in another way.

**Comment by waldo1001** [comment]
Perfect report!
Will look at it when I have time!
Thank you very much!

**Comment by waldo1001** [comment]
Totally right!
I never have instances - so I probably never tested this.  Thanks for the support!

Fixed in:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/commit/491fc3d2e24a437e944474018f9389e83171dde5

**Comment by PeterBizz** [comment]
More to come... 😎

Verzonden met mijn Windows Phone
________________________________
Van: waldo<mailto:notifications@github.com>
Verzonden: ‎13-‎12-‎2016 15:39
Aan: waldo1001/Cloud.Ready.Software.PowerShell<mailto:Cloud.Ready.Software.PowerShell@noreply.github.com>
CC: Bizzbrain | Peter Wijntjes<mailto:peter.wijntjes@bizzbrain.nl>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [waldo1001/Cloud.Ready.Software.PowerShell] Unlock-NAVApplicationObjects (#14)


Totally right!
I never have instances - so I probably never tested this. Thanks for the support!

Fixed in:
491fc3d<https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/commit/491fc3d2e24a437e944474018f9389e83171dde5>
