### ISSUE TITLE
How about a README.md in each of the (module) folders?

### ISSUE THREAD

**Issue by jhoek** [waldo1001/Cloud.Ready.Software.PowerShell#16]
How about a README.md in each of the (module) folders explaining what the scripts in that folder do? The structure may seem logical and clear to you (since you created it - over time), but the amount of information and scripts here can be quite overwhelming to the casual visitor... ;-) 

Even beter: put all documentation into your cmdlets as comment-based help (so that it can also be consulted within PowerShell), then use Get-Help to extract the information and somehow ~magically convert that to MarkDown, ready for publication on GitHub?! :-)

Thanks for considering my suggestion!

**Comment by waldo1001** [comment]
Yeah, I'm trying to do the inline help with the functions that I "touch".  Converting afterwards makes sense indeed - good idea :).

But as you can see - it's not on top of my priority list (sorry for that). But thanks for the reminder.  I'll keep this issue open just to remind myself ;-)

**Comment by jhoek** [comment]
I'm using [this](https://github.com/jhoek/Get-HelpAsMarkDown) myself for generating markdown help from documentation comments.
