### ISSUE TITLE
Can not load modules

### ISSUE THREAD

**Issue by barandeniz** [waldo1001/Cloud.Ready.Software.PowerShell#19]
---------------------------
Windows PowerShell ISE - Error
---------------------------
Failed to import the module required by command "Backup-NAVDatabase". Module name: "Cloud.Ready.Software.NAV". Error message: "Unable to find type [Microsoft.Dynamics.Nav.Model.Tools.ApplicationObjectFileInfo].".
---------------------------
OK   
---------------------------

I'am gettin this error when i try to Load modules or Refresh in PowerShell ISE.

**Comment by waldo1001** [comment]
Few questions:
- you have admin rights on the machine?
- did you try it on another machine?
- when/how did you obtain that version of the module?  Did you try to download the latest?
- did you do a complete installation of NAV?  Which parts did you leave out?

**Comment by barandeniz** [comment]
Which parts should i add ? I really do not remember which parts i left out. Yes i have admin rights,Yes i got same error on another machine. yes i just downloaded last version of your modules. the only option left is last one.

**Comment by waldo1001** [comment]
Well, from what I see in the error, is that you have problems with the client.  So I would re-install the complete client..

**Comment by waldo1001** [comment]
@barandeniz, any feedback?

**Comment by barandeniz** [comment]
Sorry, i did not have time to uninstall and reinstall the client so atm i do not have any feedback. As soon as i try, will update this issue.

**Comment by jhoek** [comment]
@barandeniz Any news to report on this? Did you manage to get it to work eventually?

**Comment by barandeniz** [comment]
@jhoek , Yes first you need to import navisions scripts.

![image](https://user-images.githubusercontent.com/6250904/68668859-2f7ae480-055a-11ea-8d75-c6ea2ed69c2f.png)
