### ISSUE TITLE
Suggestion for Get-NAVCumulativeUpdateFile.ps1

### ISSUE THREAD

**Issue by rdebath** [waldo1001/Cloud.Ready.Software.PowerShell#2]
I suggest that it's documented that you can use lots of other RSS URLs in the Get-NAVCumulativeUpdateFile.ps1 script.

This allows the script to download any of the NAV versions, except 2013r2 CU1..5.

```

                Write-Host -Object "Processing parameters $CountryCode $version $CUNo" -ForegroundColor Cyan

                $feedurl = 'https://blogs.msdn.microsoft.com/nav/tag/nav-2013/feed/'
                $feedurl = 'https://blogs.msdn.microsoft.com/nav/tag/nav-2013-r2/feed/'
                $feedurl = 'https://blogs.msdn.microsoft.com/nav/tag/nav-2015/feed/'
                $feedurl = 'https://blogs.msdn.microsoft.com/nav/tag/nav-2016/feed/'
                $feedurl = 'https://blogs.msdn.microsoft.com/nav/2014/4/feed/'
                $feedurl = 'https://blogs.msdn.microsoft.com/nav/2015/5/11/feed/'

                $feedurl = 'https://blogs.msdn.microsoft.com/nav/category/announcements/cu/feed/'
```

Perhaps even a command line option ?

**Comment by rdebath** [comment]
Looks like they've completely disabled this script by "improving the download experience".

Oh well, I suppose this request is now moot and we're force to fight through the "consumer download experience".

**Comment by waldo1001** [comment]
@rdebath , thank you for mentioning.
They indeed updated the entire download experience .. but it got better  (I think) :-).
And I changed the script to support this new way.  Just read this blogpost:

http://www.waldo.be/2016/12/09/automate-downloads-of-cumulative-updates/

**Comment by rdebath** [comment]
Thanks for the update; it seems to be working nicely, once I added the the two variations on the locale.

As the the experience without the script, It did get better; but IMO a more accurate description would be "two steps forward and one step back" !
