### ISSUE TITLE
We should add a script to open the web client instead of the windows client

### ISSUE THREAD

**Issue by SorenKlemmensen** [waldo1001/Cloud.Ready.Software.PowerShell#21]
Especially for App Development it would be handy that the web client came up when it is time to test. The windows client is kind of useless :) (Add tablet and phone client too for that matter)

I am just putting this one here as a place holder for my self or somebody else that is game for a little challenge.

**Comment by bgbak** [comment]
Are you thinking about having the script just open the browser at the end of "5_BuildAndDeployApp.ps1" in addition to opening the RTC?

**Comment by SorenKlemmensen** [comment]
Well I was thinking that we either take it out completely to open the client and make a script or step in this to open a client so everyone can select what client to open. I am writing an app at the moment and never ever use the windows client as testing here makes no sense. For Extension I can see it makes sense to test in all clients but App are for D365 and will only ever be used via the web client. So in conclusion I am not sure it even makes sense to open the client as part of this script. Maybe we just need to move it to its own script or alternative we could add a setting in the _settings.ps1 file so the user can decide or not to open a client and which one. Sorry just brainstorming at the moment. :-)

**Comment by bgbak** [comment]
I agree.
With PR #26  testing with all clients is optional and can easily be turned on/off.

**Comment by waldo1001** [comment]
I *hope* I added this with this commit:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/commit/467582ce93336e6877959940b832f9dc8f9b264b

I added the changes from #bgbak, only with some slight changes.
I added a Start-NAVWebClient
I added the ability to install a WebServerInstance with the New-NAVEnvironment
I added the remove-part in the Remove-NAVEnvironment

I'm going to close this one .. hope it sufficient.  If not, please don't hesitate to open a new issue ;-).

**Comment by waldo1001** [comment]
and .. thanks, guys! :-)
