### ISSUE TITLE
The extension script doesn't unpublish the extension 

### ISSUE THREAD

**Issue by SorenKlemmensen** [waldo1001/Cloud.Ready.Software.PowerShell#23]
When you run "5_BuildAndDeployApp.ps1" in the extension scripts the old App is not unpublished. Now I am not sure if that is done intentional, but I would suggest we get that added.

Again this as much a reminder to my self to get his done as anything else :-)

**Comment by waldo1001** [comment]
Well .. there is some "handling" in the Deploy-NAVXPackage:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/master/PSModules/Cloud.Ready.Software.NAV/Apps/Deploy-NAVXPackage.ps1

If you choose NOT to save data, it's going to unpublish.

Does that make sense?

**Comment by SorenKlemmensen** [comment]
Not a big fan of this. Doesn't seem very intuitive. That said I have a hard time to come up with something better...

**Comment by waldo1001** [comment]
I'll close it for now.  If anyone as any good idea on how to handle this better - I'm all ears ;-)
