### ISSUE TITLE
Get-NAVCumulativeUpdateFile and IE

### ISSUE THREAD

**Issue by SorenKlemmensen** [waldo1001/Cloud.Ready.Software.PowerShell#27]
I just noticed that Get-NAVCumulativeUpdateFile only works after you have run IE the first time so it has been setup. I just wanted to document it somewhere for later :-)

The error you get is
**Searching for RSS item**
_Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's 
first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. 
At C:\Users\soren\Source\Repos\Waldo\Cloud.Ready.Software.PowerShell\PSModules\Cloud.Ready.Software.NAV\Upgrade\Get-NAVCumulativeUpdateFile.ps1:47 
char:23
+         $feed = [xml](Invoke-WebRequest -Uri $feedurl)
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand_

**Comment by waldo1001** [comment]
Isn't this related with this one:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/issues/24#issuecomment-279240623

**Comment by waldo1001** [comment]
I decided to not going to invest in this function anymore. It has been too reliant on Microsoft - and Microsoft is clearly going to invest in docker ...

You are more than welcome to have a look at it.
