### ISSUE TITLE
Create button in ISE for all installed NAV versions

### ISSUE THREAD

**Issue by waldo1001** [waldo1001/Cloud.Ready.Software.PowerShell#33]
Using functions from:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/pull/32

**Comment by KristofKlein** [comment]
like this? [Mockup!]

![image](https://cloud.githubusercontent.com/assets/23500845/24093894/7b06173e-0d56-11e7-8260-46f41fe169cc.png)


I had quite some hard times to find the different versions. Most easiest for me in the end was to use a defined folder structure. Like this I can parse the Version number and if needed Language Code and CU and NAV Base Version just out of a text string.

Maybe it becomes easier to have a supporter file flying around in the ise profile folder where that kind of data is stored. like this it can also be tweaked manually in case of detection failed. 

to get the folders you just have to use the return value from the Submenus.add:

```
$MNAV = $psise.CurrentPowerShellTab.AddOnsMenu.Submenus.Add("NAVs",$null,$null)
$MNAV2015 = $MNAV.Submenus.Add("2015",$null,$null)
$MNAV2015_CU1 = $MNAV2015.Submenus.Add("CU1",$null,$null)
$MNAV2016 = $MNAV.Submenus.Add("2016",$null,$null)
$MNAV2016_CU1 = $MNAV2016.Submenus.Add("CU1",$null,$null)
$MNAV2017 = $MNAV.Submenus.Add("2017",$null,$null)
$MNAV2017_CU1 = $MNAV2017.Submenus.Add("CU1",$null,$null)
$MNAV2017_CU2 = $MNAV2017.Submenus.Add("CU2",$null,$null)
$MNAV2017_CU3 = $MNAV2017.Submenus.Add("CU3",$null,$null)
$MNAV2017_CU4 = $MNAV2017.Submenus.Add("CU4",$null,$null)
```

**Comment by waldo1001** [comment]
well .. with the functions of @Koubek , I think it makes sense to totally be generic .. .  Don't know if it's possible - but will try ;-)

**Comment by waldo1001** [comment]
too little time - Sorry.
