### ISSUE TITLE
Possible issues related to the new functions added in #32

### ISSUE THREAD

**Issue by Koubek** [waldo1001/Cloud.Ready.Software.PowerShell#35]
Hi,
I cannot see the new functions added in #32 to be present in the "Cloud.Ready.Software.NAV.psd1". Is it OK? It seems to be working generally well but I am working on some improvements (version discovery using background jobs to speed up the whole process) and those are failing just because the new functions "doesn`t exist".

**Comment by waldo1001** [comment]
You are right .. I normally only do that when I create a new module for the gallery.  I updated them, and commited:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/commit/d5f82a3084b067b8f801ddd74edf769b9e3bfec1
