### ISSUE TITLE
Doing FullInstallNAV2018 installation and starting VS-Code Developing on W1 installation

### ISSUE THREAD

**Issue by mvdheijkant** [waldo1001/Cloud.Ready.Software.PowerShell#42]
This might be a little off topic, but because you provided this script I was asking myself if you have used this script combined with VS-Code with the AL-Extension and developed on a Navsion W1 2018 environment, all on a local-VM.
I'm kind of running against a brick wall when trying to get this answered on Microsoft/AL.

I't doesn't seem to work when using W1 Symbols an trying to publish an extension.
On Azure the W1 installation works, but I can't find a difference in configuration except for using Azure-SQL and using https.

Hopefully you can confirm that a full installed local environment with W1 is supported.

**Comment by waldo1001** [comment]
I have been doing local dev successfully on all VMs I had the DVD for.  Lately, getting this DVD is not simple, as they are distributing Docker images now... .  Hard to get the DVD. :(.

Have you enabled the "development service" in the service tier?

**Comment by mvdheijkant** [comment]
I've enabled "development service". Both Symbol files are downloaded (system and W1), with configuration "locale": "W1" . But then in the "Hello World" extension, the "Customer List" page is not recognised.
After manually adding the US symbol file and changing to "locale": "US" the "Customer List" page is recognised and intellisense is working for other objects too. But when publishing, again the "Customer List" is not recognised. So I'm kind of stuck trying to get this to work using the W1 configuration.

**Comment by waldo1001** [comment]
Hi @mvdheijkant, any progress on this?
Shall I close this issue, as I din't think there is anything to fix here on my side (yet)?

**Comment by mheijkant** [comment]
I don't think this is still relevant. thanks anyway.
