### ISSUE TITLE
Create-NAVDelta.ps1 doesnt support new parameter -ExportToNewSyntax

### ISSUE THREAD

**Issue by Pieterheinevdm** [waldo1001/Cloud.Ready.Software.PowerShell#48]
Create-NAVDelta.ps1 doesn't use/support new parameter -ExportToNewSyntax in function:Compare-NAVApplicationObject. 
This parameter -ExportToNewSyntax is needed otherwise the txt2al.exe conversion will raise an error for the page extensions.

example of this error
----ERROR----
Error converting file:C:\Merge\testAL8\Create-NAVDelta\AppFiles_NewSyntax\PAG30.DELTA
The delta file was not generated with ExportToNewSyntax flag
----ERROR----

**Comment by waldo1001** [comment]
I added the parameter, but I wasn't able to test .. can you? (you probably need to update the function manually in your current version of the module...)

**Comment by Pieterheinevdm** [comment]
Thank you Waldo, just tested it this solution works
