### ISSUE TITLE
using "import-module sqlps" in several function

### ISSUE THREAD

**Issue by mheijkant** [waldo1001/Cloud.Ready.Software.PowerShell#49]
I see you use import-module sqlps in several module functions. Why is that? 
Because now i'm kind of forced to only use sqlps instead of sqlserver, when using your modules
The sqlps module is kind of old, and the sqlserver module replaces this.
also sqlps can only be used if you have an sql-installation in place while sqlserver can be imported from psgallery. why not remove sqlps module from your functions and leave it up to the user to import sqlps or sqlserver.

**Comment by waldo1001** [comment]
I have to do that, yes - thanks for this issue - I will try to find time for it.
in the meantime - don't hold yourself to fork/pullrequest a solution ;-)
