### ISSUE TITLE
Import-NAVModules does not import from BC modules

### ISSUE THREAD

**Issue by MortenRa** [waldo1001/Cloud.Ready.Software.PowerShell#55]
It doesn´t seems like Import-Navmodules looks for BC on prem folder Microsoft switch name 
from
Microsoft Dynamics NAV
to
Microsoft Dynamics 365 Business Central

Please update Get-NAVModuleVersions.ps1 to support this

**Comment by waldo1001** [comment]
Done!
thanks for this!
