### ISSUE TITLE
Cannot bind argument to parameter 'versions' because it is null

### ISSUE THREAD

**Issue by MortenRa** [waldo1001/Cloud.Ready.Software.PowerShell#57]
When using 
Import-NavModules

Keep getting this error: Cannot bind argument to parameter 'versions' because it is null
first time CRS is installed

But BC version 14 is installed

**Comment by waldo1001** [comment]
I'm publishing a new version as we speak - should be solved now (hopefully) ;)

**Comment by waldo1001** [comment]
And - thanks for taking the time to log the issue ;-)
