### ISSUE TITLE
Get-NAVCumulativeUpdateFile has issues with no CU web pages.

### ISSUE THREAD

**Issue by GreatScott000** [waldo1001/Cloud.Ready.Software.PowerShell#68]
Hi @waldo1001, Microsoft have re-designed the cumulative update release pages, so the Get-NAVCumulativeUpdateFile function does not work.  I will update the script in the next week or so and do a pull request.  I don't know about anyone else but I still find this function useful, particularly for on-premise installations.

**Comment by waldo1001** [comment]
that would be very much appreciated!
I don't use it anymore myself (100% docker, even customers ;-))... so I really appreciate you updating the code for this!
