### ISSUE TITLE
Import Modules to Visual Studio Code

### ISSUE THREAD

**Issue by barandeniz** [waldo1001/Cloud.Ready.Software.PowerShell#8]
Hello, how can we import these modules to Visual Studio Code ?

**Comment by waldo1001** [comment]
Well, I'm not too familiar yet with VSCode .. but working on it ;-).  If updates or descriptions are needed, I will add it here.

**Comment by javisoft** [comment]
Hello,
I was wondering the same thing! 
I tried this:
I'm using a PowerShell [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) from Microsoft. I just forked the modules and opened Visual Studio to clone it locally.Then, I opened the folder in Visual Studio "Code". I'm going to try if I can debug and run the files like I normally do with others scripts.

**Comment by waldo1001** [comment]
Apparently, when you use my modules from PowerShellGet, it just works in VSCode.. (in combination with the PowerShell extension, of course).  
@barandeniz , can you try that approach?

**Comment by SorenKlemmensen** [comment]
We could create an extension for VSCode and tie it to the PowerShell, but generally you can just run them directly.

**Comment by javisoft** [comment]
I've been using the VSCode Powershell extension for few months, and all the scripts run perfectly. The Debug also works fine.

**Comment by bgbak** [comment]
By using the PowerShell extension for VS Code this should not be an issue.
Also check this great blog post for a introduction to debugging PowerShell scripts in VS Code.
https://blogs.technet.microsoft.com/heyscriptingguy/2017/02/06/debugging-powershell-script-in-visual-studio-code-part-1/

**Comment by jhoek** [comment]
@barandeniz Are you still having trouble using the modules from VS Code? If not, perhaps you should close this issue?

**Comment by waldo1001** [comment]
I kind of lost track of this issue ..
But for the past year, I only have been using VSCode for PowerShell, and never had any issues with these modules.  Can anyone confirm that all is fine (assuming you all download the modules from the PowerShellGallery)?

**Comment by waldo1001** [comment]
I'll close for now.  Use the modules from PowerShell Gallery:
`Find-module | where author -eq "waldo" | install-module -force`

I'll close for now.
