### ISSUE TITLE
New-NAVEnvironment

### ISSUE THREAD

**Issue by epernst** [waldo1001/Cloud.Ready.Software.PowerShell#9]
Just trying to run New-NAVEnvironment with "my scripts" with the new NAV 2017 RTM.

Restoring database NAV100_NA_RTM
RESTORE DATABASE [NAV100_NA_RTM] FROM DISK = N'C:\Core\Backup\NA.BAK' WITH FILE = 1,
    MOVE N'Demo Database NAV (10-0)_Data' TO N'C:\Program Files\Microsoft SQL Server\MSSQL12.NAVDEMO\MSSQL\DATA\NAV100_NA_RTM_1.mdf',
        MOVE N'Demo Database NAV (10-0)_Log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL12.NAVDEMO\MSSQL\DATA\NAV100_NA_RTM_2.ldf',
        NOUNLOAD, REPLACE, STATS = 5
Invoke-Sqlcmd : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
Converting database 'NAV100_NA_RTM' from version 706 to the current version 782.
At C:\Users\epernst\Documents\Cloud.Ready.Software.PowerShell\PSModules\Cloud.Ready.Software.SQL\Restore-SQLBackupFile.ps1:60 char:13
-     $null = Invoke-Sqlcmd -Query $RestoreSQLString -ServerInstance "$DatabaseSer ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
  - FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand

Figuring that it's trying to upgrade the SQL version and that's what failing. Then I went into SQL, manually upgrade the version from 110 to 120 and created a new *.BAK file - instead of the one supplied by Microsoft on the DVD that I used before.
Running it with the new backup already in version 120 allows me to run the function again. 

But exactly what was changed here? In NAV 2017 Limited Beta the bak files supplied were also version 110, but here it worked fine.

**Comment by waldo1001** [comment]
Just tried this:
New-NAVEnvironment -ServerInstance 'TestNewNAVEnvironmentCmdLet' -BackupFile 'E:\SQLDemoDatabase\CommonAppData\Microsoft\Microsoft Dynamics NAV\100\Database\Demo Database NAV (10-0).bak' -EnablePortSharing

so straight from the DVD .. and worked.

Make sure you have installed NAV 2017, have loaded the NAVAdmin module in PowerShell .. and obviously my scripts :-) .. before you run the function.. .

**Comment by epernst** [comment]
Sure, everything else worked just fine. And as written using a bak-file created after I upgraded to 120 works fine.

**Comment by SorenKlemmensen** [comment]
Is it a big backup your are restoring? Just wondering. I did not test this outside restoring the databases from the product DVD and that works. That said you are getting a time out so could it be the database size?

**Comment by waldo1001** [comment]
I should have handled the timeouts in these scripts with using the default SQL-Cmdlets - with endless timeout.. .

**Comment by waldo1001** [comment]
afaik, this has been fixed along the line.  Please let me know if it isn't.  I'll close for now.
